resend lab3
Sosnin-Artur/ITandDDP pull request #3
Opened 2022-04-12 08:44 UTC by Sosnin-Artur

2022-04-18 21:42 UTC, katetushkan requested changes
Where is CSS ?
There is no mobile version
<img width="358" alt="Screenshot 2022-04-18 at 23 42 07" src="https://user-images.githubusercontent.com/43992068/163882377-b2a68539-e4c5-4576-b344-4b125a010109.png">
(

2022-04-18 21:42 UTC, katetushkan commented on chat.html
> +        <h3 id="room-name">RoomName</h3>
u can't use `<h3>` without using `<h2>`

2022-04-18 21:42 UTC, katetushkan commented on chat.html
> +        <h3 id="room-name">RoomName</h3>
I think also, that u forget to redeploy.

2022-04-19 22:30 UTC, Sosnin-Artur commented
deploy address: https://checking-lab.herokuapp.com/

2022-05-08 11:23 UTC, katetushkan commented on css/style.css
> +	font-size: 3vw;
That's a bad practice. Font size can be the same. You need to adapt element and layout dimensions instead.

2022-05-08 11:25 UTC, katetushkan requested changes
<img width="467" alt="image" src="https://user-images.githubusercontent.com/43992068/167293888-3bf6c10e-9f14-4316-ba08-7c1ec5cd9276.png">

This is not a mobile version. You just scaled down the website. Now try to hit buttons or inputs with your finger. It will be pretty tough task for you I'm sure.

Mobile version assumes your UI is adapted for smaller screen sizes. Take a look at mobile apps and mobile version of websites (take Twitter as example).

Drop percentages, drop `vw` units.

2022-05-08 11:25 UTC, katetushkan commented on css/style.css
> +	padding: 1% 3% ;
Percentage values for margins and paddings are also not a good idea.

2022-05-08 11:25 UTC, katetushkan commented on css/style.css
> +	margin: center;
Hm?

2022-05-12 10:23 UTC, katetushkan approved these changes
<kbd>8</kbd>

2022-05-12 10:24 UTC, katetushkan approved these changes

2022-05-14 07:16 UTC, closed without merging